models:
- api_base: http://host.docker.internal:11434/
  kwargs:
    n: 1
    temperature: 0
  model: ollama/llama3.2-vision:latest
provider: litellm_llm
timeout: 120
type: llm
---
models:
- api_base: http://host.docker.internal:11434/
  model: ollama/nomic-embed-text:latest
  timeout: 120
provider: litellm_embedder
type: embedder
---
endpoint: http://wren-ui:3000/
provider: wren_ui
type: engine
---
embedding_model_dim: 768
location: http://qdrant:6333/
provider: qdrant
recreate_index: false
timeout: 120
type: document_store
---
pipes:
- document_store: qdrant
  embedder: litellm_embedder.ollama/nomic-embed-text:latest
  name: db_schema_indexing
- document_store: qdrant
  embedder: litellm_embedder.ollama/nomic-embed-text:latest
  name: historical_question_indexing
- document_store: qdrant
  embedder: litellm_embedder.ollama/nomic-embed-text:latest
  name: table_description_indexing
- document_store: qdrant
  embedder: litellm_embedder.ollama/nomic-embed-text:latest
  llm: litellm_llm.ollama/llama3.2-vision:latest
  name: db_schema_retrieval
- document_store: qdrant
  embedder: litellm_embedder.ollama/nomic-embed-text:latest
  name: historical_question_retrieval
- engine: wren_ui
  llm: litellm_llm.ollama/llama3.2-vision:latest
  name: sql_generation
- engine: wren_ui
  llm: litellm_llm.ollama/llama3.2-vision:latest
  name: sql_correction
- engine: wren_ui
  llm: litellm_llm.ollama/llama3.2-vision:latest
  name: followup_sql_generation
- llm: litellm_llm.ollama/llama3.2-vision:latest
  name: sql_summary
- engine: wren_ui
  llm: litellm_llm.ollama/llama3.2-vision:latest
  name: sql_answer
- engine: wren_ui
  llm: litellm_llm.ollama/llama3.2-vision:latest
  name: sql_breakdown
- engine: wren_ui
  llm: litellm_llm.ollama/llama3.2-vision:latest
  name: sql_expansion
- llm: litellm_llm.ollama/llama3.2-vision:latest
  name: sql_explanation
- engine: wren_ui
  llm: litellm_llm.ollama/llama3.2-vision:latest
  name: sql_regeneration
- llm: litellm_llm.ollama/llama3.2-vision:latest
  name: semantics_description
- engine: wren_ui
  llm: litellm_llm.ollama/llama3.2-vision:latest
  name: relationship_recommendation
- llm: litellm_llm.ollama/llama3.2-vision:latest
  name: question_recommendation
- document_store: qdrant
  embedder: litellm_embedder.ollama/nomic-embed-text:latest
  llm: litellm_llm.ollama/llama3.2-vision:latest
  name: question_recommendation_db_schema_retrieval
- engine: wren_ui
  llm: litellm_llm.ollama/llama3.2-vision:latest
  name: question_recommendation_sql_generation
- document_store: qdrant
  embedder: litellm_embedder.ollama/nomic-embed-text:latest
  llm: litellm_llm.ollama/llama3.2-vision:latest
  name: intent_classification
- llm: litellm_llm.ollama/llama3.2-vision:latest
  name: data_assistance
- document_store: qdrant
  embedder: litellm_embedder.ollama/nomic-embed-text:latest
  name: sql_pairs_indexing
- document_store: qdrant
  embedder: litellm_embedder.ollama/nomic-embed-text:latest
  name: sql_pairs_deletion
- document_store: qdrant
  embedder: litellm_embedder.ollama/nomic-embed-text:latest
  llm: litellm_llm.ollama/llama3.2-vision:latest
  name: sql_pairs_retrieval
- llm: litellm_llm.ollama/llama3.2-vision:latest
  name: preprocess_sql_data
- engine: wren_ui
  name: sql_executor
- llm: litellm_llm.ollama/llama3.2-vision:latest
  name: chart_generation
- llm: litellm_llm.ollama/llama3.2-vision:latest
  name: chart_adjustment
- llm: litellm_llm.ollama/llama3.2-vision:latest
  name: sql_question_generation
- llm: litellm_llm.ollama/llama3.2-vision:latest
  name: sql_generation_reasoning
type: pipeline
---
settings:
  allow_using_db_schemas_without_pruning: false
  column_indexing_batch_size: 50
  development: false
  langfuse_enable: true
  langfuse_host: https://cloud.langfuse.com
  logging_level: DEBUG
  port: 5556
  query_cache_maxsize: 1000
  query_cache_ttl: 3600
  table_column_retrieval_size: 100
  table_retrieval_size: 10
